### ISSUE TITLE
Question: is there a  common way to speed up pipelines?

### ISSUE THREAD

**Issue by Peedee2002** [terraform-google-modules/terraform-example-foundation#1258]
Hi, I work for a team that manages an organisation with about 10 business units, managed under the `4-projects` step.
Running the build step when `4-projects` is modified has been getting significantly slower as we add more projects.
This makes sense, but I want to improve this situation as the pipeline has gotten to 25 minutes per run for just that planning step. 
Our pipeline uses the provided [tf-wrapper](https://github.com/terraform-google-modules/terraform-example-foundation/blob/e1605bd0d332c99158270111d021463c65fe7c7d/build/tf-wrapper.sh#L4) file to run the sequence of init, plan, validate and apply. Adding paralellism to the script (by running all inits concurrently, then all plans concurrently, then all validates concurrently) did speed this up to below 10 minutes, which is great.
However, this required us to modify the tf-wrapper.sh significantly and convert it to python. Also, it now requires all locks to be held at once. This means that only 1 plan or apply can run at a time, or wait for the lock. Is there any other approach that is used for managing this?

This repo is modified often, often for granting access to google APIs or giving specific permissions to primary accounts. Are there better ways of handling these tasks?

**Comment by eeaton** [comment]
Hi @Peedee2002, here are a few options you might also consider, although the right choice for your circumstance will vary based on your operational requirements, like which capabilities your organization is willing to delegate to decentralized workload teams vs keeping in a centralized platform team.

- since you already have 10 business units , it might make sense to shard the monolithic project repo for projects into project repos for individual business units. This is a common fix I've seen customers adopt at large scale.
    - this can also be useful if different business units' repos are managed by different teams or have different forks of your CI/CD pipeline. But even if there is only one team that manages the project factory for all business units, this can speed up the plan and apply stages for individual repos.
- depending on your operations, you might allow workload developers to set some attributes like API enablement in their own workload-specific repos, rather than asking the central platform team to set those as part of the project factory
    - this could reduce some of the high frequency requests to the centralized platform team without sacrificing developer velocity
    - some platform teams prefer to enable APIs centrally as a control against workload teams enabling services not approved by the platform team. If this is a concern in your org, you could enforce the org policy  [ restrict resource service usage ](https://cloud.google.com/resource-manager/docs/organization-policy/restricting-resources) to enforce that only an approved allowlist of APIs can be enabled in the org, and allow developers to enable the APIs themselves within that list.

Hope that helps. I'll close this issue for now but feel free to re-open if needed.

**Comment by eeaton** [comment]
One other tactic that a colleague suggested:
- Depending on where the bottleneck is, another tactical option to speed up might also be [leveraging provider cache](https://developer.hashicorp.com/terraform/cli/config/config-file#plugin_cache_dir), disable refresh in some cases/have some logic to only actuate root modules with a diff and have a separate periodic pipeline for full reconciliation.
