### ISSUE TITLE
3-networks: Compute instance in shared VPC cannot connect to Internet when NAT is enabled

### ISSUE THREAD

**Issue by vovinacci** [terraform-google-modules/terraform-example-foundation#299]
When compute instance has `egress-internet` tag, it still cannot access Internet as the only egress firewall rule is `fw-${var.environment_code}-shared-base-65535-e-d-all-all-all` for both [base_shared_vpc](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/modules/base_shared_vpc/firewall.tf#L21-L43) and [restricted_shared_vpc](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/modules/restricted_shared_vpc/firewall.tf#L21-L43).

This may be fixed by adding one more optional rule similar to the one below

```hcl
// Allow egress traffic when NAT is enabled
resource "google_compute_firewall" "allow_nat_gateways_egress" {
  count     = var.nat_enabled ? 1 : 0
  name      = "fw-${var.environment_code}-shared-base-1003-e-a-all-allow-nat-all-all"
  network   = module.main.network_name
  project   = var.project_id
  direction = "EGRESS"
  priority  = 1003

  dynamic "log_config" {
    for_each = var.firewall_enable_logging == true ? [{
      metadata = "INCLUDE_ALL_METADATA"
    }] : []

    content {
      metadata = log_config.value.metadata
    }
  }

  allow {
    protocol = "all"
  }

  destination_ranges = ["0.0.0.0/0"]

  target_tags = ["egress-internet"]
}
```

What do you think? I've tested this, and it seems to work. Can create a PR if all looks legit.

**Comment by rjerrems** [comment]
Hi @vovinacci - we intentionally have a hardened security baseline, so that users add specific firewall rules as required to suit their use case as this is security best practice. We explicitly add a deny egress rule here for that purpose:

https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks/modules/base_shared_vpc/firewall.tf#L21

In the default configuration for a VPC, egress is allowed https://cloud.google.com/vpc/docs/firewalls#default_firewall_rules

Because this example foundation is implementing security best practices, I don't think we can add this - does that make sense?

**Comment by vovinacci** [comment]
Hi @rjerrems. Thanks much for the explanation, that makes sense. I didn't really understand the purpose at first.
