### ISSUE TITLE
Missing information about terraform validator on READMEs

### ISSUE THREAD

**Issue by amandakarina** [terraform-google-modules/terraform-example-foundation#360]
Improves information about terraform-validator on READMEs for user experience:

- Explain the necessity of a project already created for validator, this project must be created before execute the terraform validator and the user must have access.
- Inform the minimal version of terraform validator (2021-01-21)

**Comment by renato-rudnicki** [comment]
It is also necessary rename the terraform-validor file. 
Example: From terraform-validator-windows-amd64 to `terraform-validator`

**Comment by renato-rudnicki** [comment]
On terraform-validator section, it needs to be clear that we need to follow only the steps from section **Install Terraform Validator** on documentation https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#install-terraform-validator.

**Comment by daniel-cit** [comment]
Fixed by: https://github.com/terraform-google-modules/terraform-example-foundation/pull/465 , https://github.com/terraform-google-modules/terraform-example-foundation/pull/454 , https://github.com/terraform-google-modules/terraform-example-foundation/pull/397, and https://github.com/terraform-google-modules/terraform-example-foundation/pull/263
