### ISSUE TITLE
MIssing app_infra_pipeline_cloudbuild_sa variable on environments tfvars examples in step 4-projects

### ISSUE THREAD

**Issue by amandakarina** [terraform-google-modules/terraform-example-foundation#365]
The required variable `app_infra_pipeline_cloudbuild_sa` is not present on tfvars example files and there are no mention in the main README.

**Comment by daniel-cit** [comment]
The problem here is a bit more complex that it appears at first look.

As we can see by the way the variable is used in the test build code:

https://github.com/terraform-google-modules/terraform-example-foundation/blob/dbd4c73a1aeab9aeabbfddbab961aff78db05289/test/fixtures/projects/main.tf#L36

The variable is actually the output of the `shared` folder for that business unit and when we use **Cloud Build** to deploy the foundation, `shared` is deployed at the same time as `production` is deployed and `shared` has not been deployed at the time `development` and `non-production` are run.

In this case we would need to do something similar to what is done in step 3-networks:

https://github.com/terraform-google-modules/terraform-example-foundation/blob/88cbe2c513cd854c7d899a4b77851af3fda25f92/3-networks/README.md#L55

Which is to manually deploy the `shared` folder for both business units before the deployment of `development`, `non-production` and `production`.

@bharathkkb @rjerrems  do we have any alternative to this solution ?

**Comment by bharathkkb** [comment]
@daniel-cit yes this was my expected approach (similar to 3-networks shared)

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/374
