### ISSUE TITLE
 googleapi: Error 400: Precondition check failed., failedPrecondition

### ISSUE THREAD

**Issue by louiskimlevu** [terraform-google-modules/terraform-example-foundation#378]
Hello,

I am receiving this error when running tf apply for the part 2 (environments). I saw this issue can come from limits of the free trial but I already enabled the standard subscription in my organization.

```
Error: Error setting billing account "011EE1-C53D47-660F3B" for project "projects/prj-d-shared-base-9561": googleapi: Error 400: Precondition check failed., failedPrecondition

  on .terraform/modules/env.base_shared_vpc_host_project/modules/core_project_factory/main.tf line 96, in resource "google_project" "main":
  96: resource "google_project" "main" {

**Comment by louiskimlevu** [comment]
From the console I have a quota error. I sent a quota request but it might be useful to add this info as prerequisite.
![image](https://user-images.githubusercontent.com/57093546/111445808-b8092680-8746-11eb-9cfe-2063ece05d91.png)

**Comment by m0ps** [comment]
That's a limitation of the trial account.
In my case, they requested a top-up account with $50, and then the quota will be increased.

**Comment by mosqgft** [comment]
Same here. You need to open a request to increase quota and put USD 50.

**Comment by gjj** [comment]
Wow thanks for this! I wish I've seen this earlier - it seems like setting this on a fresh Cloud Identity organisation, I hit the limit at `1-org`. Actually, wouldn't it be better to leave a note in `1-org`'s pre-requisites?

**Comment by rajesh-nitc** [comment]
I paid $10 for additional 10 projects. Sharing in case someone wants to pay less for less.

**Comment by morgante** [comment]
Just to be clear, projects themselves are free.

**Comment by gjj** [comment]
Thanks all for the clarifications! Understood that the topup will be applied to future usage, while unlocking more projects at the same time.

While I'm waiting for the quota increase, I have another question: so my `1-org` Cloud Build deployment pipeline created a project halfway and was unable to link my billing account due to the original quota, as it seems like I'm getting `Error 409: Requested entity already exists, alreadyExists.`

Should I delete that specific project manually or just let Terraform do its job once I get my quota increase?
