### ISSUE TITLE
Move hard-coded network ranges from .tf files to tfvars 

### ISSUE THREAD

**Issue by aarturm** [terraform-google-modules/terraform-example-foundation#413]
Network ranges are hard coded in [.tf file](https://github.com/terraform-google-modules/terraform-example-foundation/blob/0d315491bc3ad7b9578b40042ec97907c4b69cd5/3-networks/envs/development/main.tf#L28-L71). I think it would be good to configure them with variables.tf/terraform.tfvars instead. 
What do you think?

**Comment by rjerrems** [comment]
Hi @aarturm - thanks for the feedback. The ranges are intended to be in the file, as this is a reference implementation of how to build a foundation so that someone reading the code can quickly understand what it is doing, which is why we have avoided adding these as variables/tfvars as this can have the affect of making the code less readable/representative of a real deployment.

If we receive more feedback that this creates a negative user experience, we will consider changing this in a future release.
