### ISSUE TITLE
Split common stage into two separate stages implementing common interface

### ISSUE THREAD

**Issue by langleyce** [terraform-google-modules/terraform-example-foundation#671]
### TL;DR

Size: L

**Comment by bharathkkb** [comment]
Currently we have a single networking stage `3-networks` with a flag `enable_hub_and_spoke` to switch between two networking architectures. However this has resulted in additional complexity due to intertwined codepaths and module conditionals. 

We should instead have parallel `3-networks-dual-svpc` and `3-networks-hub-and-spoke`. Environments can be nested under each reference architecture like `3-networks-hub-and-spoke/envs` and will invoke a `base_env` located in respective `3-networks-arch/modules/base_env`. Initially there will be some code duplication in `3-networks-${arch}/modules` and we can switch to templating from a common internal `autogen/3-networks` if necessary.

**Comment by daniel-cit** [comment]
Hi @bharathkkb we have the `enable_hub_and_spoke` flag in two other steps:

**1-org**

- https://github.com/terraform-google-modules/terraform-example-foundation/blob/3e2ca413d2fd57c309748109f56008be2503ff9a/1-org/envs/shared/projects.tf#L205-L212
- https://github.com/terraform-google-modules/terraform-example-foundation/blob/3e2ca413d2fd57c309748109f56008be2503ff9a/1-org/envs/shared/projects.tf#L244-L250

**4-projects**

- https://github.com/terraform-google-modules/terraform-example-foundation/blob/3e2ca413d2fd57c309748109f56008be2503ff9a/4-projects/modules/single_project/main.tf#L19
- https://github.com/terraform-google-modules/terraform-example-foundation/blob/3e2ca413d2fd57c309748109f56008be2503ff9a/4-projects/modules/single_project/data.tf#L22-L26

Should we keep these flags?

**Comment by bharathkkb** [comment]
@daniel-cit I think we discussed this offline
For 1-org we can keep it for now and just do networking stage, in the future we may move it to shared.
For 4-projects, we can refactor after we switch to remote state.
