### ISSUE TITLE
Convert to bpt skeleton for all stages 

### ISSUE THREAD

**Issue by langleyce** [terraform-google-modules/terraform-example-foundation#686]
### TL;DR

Size: M

**Comment by bharathkkb** [comment]
@daniel-cit some ideas around what I am thinking we could do to use the new framework
- For each stage create a top level test- `TestBootstrap`, `TestOrg` ...
- Each test will use  [WithTFDir](https://pkg.go.dev/github.com/GoogleCloudPlatform/cloud-foundation-toolkit/infra/blueprint-test/pkg/tft#WithTFDir) option to point to the correct TF config location
- For stages with multiple envs (or shared), we can use a table test to pass in WithTFDir paths for each env with `shared` first

Lets do the backend bucket as a follow up since we will need to leverage partial configuration via `-backend-config` which we will need to expose in the test framework if its not possible via envvars.
