### ISSUE TITLE
0-bootstrap Cloudbuild step#1 error

### ISSUE THREAD

**Issue by jacek-git** [terraform-google-modules/terraform-example-foundation#709]
### TL;DR

I get below error message during 1st step of 

Build log: 
│ ERROR: build step 1 "europe-central2-docker.pkg.dev/prj-b-cicd-1ac5/prj-tf-runners/terraform" failed: step exited with non-zero status: 1
...
Already have image: europe-central2-docker.pkg.dev/prj-b-cicd-1ac5/prj-tf-runners/terraform
standard_init_linux.go:228: exec user process caused: no such file or directory

### Terraform Configuration

```hcl
Steps from: https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap
```

### Terraform Version

```sh
terraform --version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.18.0
+ provider registry.terraform.io/hashicorp/google-beta v4.18.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

**Comment by bharathkkb** [comment]
Hi @jacek-git thanks for the report!
Since you are on `windows_amd64` this  might be due to https://github.com/terraform-google-modules/terraform-example-foundation/issues/694. Could see if that workaround fixes the issue? Feel free to reopen if it doesn't. If it is we will track the original issue for long term fix.
